LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE :=  Gcam62Advanced190910_oneplus-msm8998
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := Gcam_6.2.030_Advanced_V2.2.2beta2.190910.1840.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_OVERRIDES_PACKAGES := Snap Camera2
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
